Allow missing image

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -10,7 +10,7 @@ jobs:
       - name: Log Into Registry
         run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
       - name: Pull Cache
-        run: docker pull ghcr.io/${GITHUB_REPOSITORY}:latest
+        run: docker pull ghcr.io/${GITHUB_REPOSITORY}:latest || echo "Cache not found"
       - name: Build Image
         run: docker build . --tag ghcr.io/${GITHUB_REPOSITORY}:latest --cache-from ghcr.io/${GITHUB_REPOSITORY}:latest
       - name: Push Image
